-- ==========================================
-- SIA REKONSILIASI BANK - SUPABASE (PostgreSQL)
-- ==========================================

-- ---------- 1. MASTER ----------
create table if not exists users (
    id_user    bigint generated by default as identity primary key,
    nama_user  varchar(100) not null,
    role       varchar(20)  not null check (role in ('Akuntan','Manajer')),
    email      varchar(100) unique not null,
    password   varchar(255) not null
);

create table if not exists bank_accounts (
    id_account     bigint generated by default as identity primary key,
    nomor_rekening varchar(30) unique not null,
    nama_bank      varchar(50) not null,
    mata_uang      varchar(5) default 'IDR'
);

-- ---------- 2. TRANSAKSI INTERNAL & EKSTERNAL ----------
create table if not exists buku_besar_kas (
    id_internal         bigint generated by default as identity primary key,
    id_account          bigint references bank_accounts(id_account) on delete cascade,
    tanggal             date not null,
    no_referensi        varchar(50) not null,
    keterangan          text not null,
    jenis_transaksi     varchar(10) not null check (jenis_transaksi in ('Masuk','Keluar')),
    nominal             numeric(15,2) not null check (nominal > 0),
    status_rekonsiliasi varchar(10) default 'Unmatched' check (status_rekonsiliasi in ('Unmatched','Matched')),
    created_at          timestamptz default now()
);

create table if not exists rekening_koran_bank (
    id_bank             bigint generated by default as identity primary key,
    id_account          bigint references bank_accounts(id_account) on delete cascade,
    tanggal_bank        date not null,
    keterangan_bank     text not null,
    jenis_mutasi        varchar(5) not null check (jenis_mutasi in ('CR','DB')),
    nominal_bank        numeric(15,2) not null check (nominal_bank > 0),
    status_rekonsiliasi varchar(10) default 'Unmatched' check (status_rekonsiliasi in ('Unmatched','Matched')),
    nama_file_source    varchar(100) not null
);

-- ---------- 3. INTI REKONSILIASI ----------
create table if not exists hasil_rekonsiliasi (
    id_rekon           bigint generated by default as identity primary key,
    id_internal        bigint unique references buku_besar_kas(id_internal) on delete set null,
    id_bank            bigint unique references rekening_koran_bank(id_bank) on delete set null,
    id_user            bigint references users(id_user),
    tanggal_rekon      timestamptz default now(),
    metode_rekon       varchar(10) not null check (metode_rekon in ('Auto','Manual')),
    keterangan_selisih varchar(255)
);

create table if not exists jurnal_penyesuaian (
    id_jurnal      bigint generated by default as identity primary key,
    id_rekon       bigint references hasil_rekonsiliasi(id_rekon) on delete cascade,
    tanggal_jurnal date not null,
    kode_akun      varchar(20) not null,
    nama_akun      varchar(100) not null,
    posisi         varchar(10) not null check (posisi in ('Debit','Kredit')),
    nominal        numeric(15,2) not null check (nominal > 0)
);

-- ---------- 4. INDEX ----------
create index if not exists idx_bbk_status on buku_besar_kas(id_account, status_rekonsiliasi);
create index if not exists idx_rkb_status on rekening_koran_bank(id_account, status_rekonsiliasi);

-- ---------- 5. RLS (demo: public) ----------
alter table users               enable row level security;
alter table bank_accounts       enable row level security;
alter table buku_besar_kas      enable row level security;
alter table rekening_koran_bank enable row level security;
alter table hasil_rekonsiliasi  enable row level security;
alter table jurnal_penyesuaian  enable row level security;

do $$ declare t text;
begin
  foreach t in array array['users','bank_accounts','buku_besar_kas',
                             'rekening_koran_bank','hasil_rekonsiliasi','jurnal_penyesuaian']
  loop
    execute format('create policy "public_all_%s" on %I for all using (true) with check (true);', t, t);
  end loop;
end $$;

-- ---------- 6. SEED DATA ----------
insert into users (nama_user, role, email, password) values
    ('Budi Akuntan','Akuntan','budi@demo.id','123'),
    ('Sari Manajer','Manajer','sari@demo.id','123')
on conflict (email) do nothing;

insert into bank_accounts (nomor_rekening, nama_bank, mata_uang) values
    ('1234567890','BCA','IDR'),
    ('9876543210','Mandiri','IDR')
on conflict (nomor_rekening) do nothing;

insert into buku_besar_kas (id_account, tanggal, no_referensi, keterangan, jenis_transaksi, nominal) values
    (1, current_date - 5, 'INV-001', 'Penerimaan dari PT ABC',  'Masuk',  5000000),
    (1, current_date - 4, 'INV-002', 'Pembayaran supplier XYZ', 'Keluar', 2500000),
    (1, current_date - 3, 'INV-003', 'Penerimaan dari PT DEF',  'Masuk',  1800000),
    (1, current_date - 2, 'INV-004', 'Pembayaran listrik',      'Keluar',  750000)
on conflict do nothing;

insert into rekening_koran_bank (id_account, tanggal_bank, keterangan_bank, jenis_mutasi, nominal_bank, nama_file_source) values
    (1, current_date - 4, 'TRF CR PT ABC',       'CR', 5000000, 'bca_sep.csv'),
    (1, current_date - 3, 'TRF DB SUPPLIER XYZ', 'DB', 2500000, 'bca_sep.csv'),
    (1, current_date - 2, 'TRF CR PT DEF',       'CR', 1800000, 'bca_sep.csv'),
    (1, current_date - 1, 'BIAYA ADM BANK',      'DB',   15000, 'bca_sep.csv'),
    (1, current_date - 1, 'BUNGA TABUNGAN',      'CR',   25000, 'bca_sep.csv')
on conflict do nothing;